# Generated by Django 5.0.4 on 2024-04-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiara', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='genre',
            field=models.CharField(choices=[('masculin', 'masculin'), ('feminin', 'feminin')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
